ignore:
  - "tests"
  - "*/tests/*"
  - "*/test_*"
  - "**/migrations/*"
  - "*/venv/*"
  - "*/env/*"
  - "*/.venv/*"
  - "*/node_modules/*"
  - "*/vendor/*"
  - "*/lib/*"
  - "*/dist/*"
  - "*/build/*"
  - "*/__pycache__/*"
  - "*.pyc"
  - "*/static/*"
  - "*/locale/*"
  - "*/docs/*"
  - "setup.py"
