version: '3'

services:
  web:
    hostname: web
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: pmg_flask
    depends_on:
      - postgres
      - elastic
    volumes:
      - .:/app
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://pmg:pmg@postgres/pmg?client_encoding=utf8
      - ES_SERVER=http://elastic:9200
      - SENTRY_DSN=https://15f79f6945ff4d4f8ac103e6a9c2f26d@sentry.io/1489874
    ports:
      - "5000:5000"
    command: python app.py runserver
    extra_hosts:
      - "pmg.test:127.0.0.1"
      - "api.pmg.test:127.0.0.1"

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=pmg
      - POSTGRES_DB=pmg
      - POSTGRES_PASSWORD=pmg
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5431:5432"

  elastic:
    image: elastic
    build:
      context: .
      dockerfile: docker-elasticsearch
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  db-data:
  es-data:
