FROM python:3.8
ENV PYTHONUNBUFFERED 1
RUN mkdir /app
COPY requirements.txt /app/
RUN pip install -r /app/requirements.txt
COPY . /app/
# Set WORKDIR after installing, so that src dir isn't created then overwritten
# by development mount
WORKDIR /app
COPY ./entrypoint /entrypoint
RUN sed -i 's/\r//' /entrypoint
RUN chmod +x /entrypoint
ENTRYPOINT ["/entrypoint"]
