version: '3'

services:
  redis:
    image: redis:5.0.14
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
  web:
    hostname: web
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: pmg_flask
    depends_on:
      - postgres
      - elastic
      - redis
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG_CACHE=true
      - REDIS_URL=redis://redis:6379/0
      - SQLALCHEMY_DATABASE_URI=postgresql://pmg:pmg@postgres/pmg?client_encoding=utf8
      - ES_SERVER=http://elastic:9200
    ports:
      - "5000:5000"
    command: python app.py runserver
    extra_hosts:
      - "pmg.test:127.0.0.1"
      - "api.pmg.test:127.0.0.1"

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=pmg
      - POSTGRES_DB=pmg
      - POSTGRES_PASSWORD=pmg
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5431:5432"

  elastic:
    image: elastic
    build:
      context: .
      dockerfile: docker-elasticsearch
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  db-data:
  es-data:
  redis-data:
