"""add committee_meeting_attendance table

Revision ID: 184fe40b1da0
Revises: 1c6a96c17073
Create Date: 2015-07-15 09:40:28.531038

"""

# revision identifiers, used by Alembic.
revision = '184fe40b1da0'
down_revision = '1c6a96c17073'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee_meeting_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alternate_member', sa.Boolean(), nullable=True),
    sa.Column('chairperson', sa.Boolean(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table(u'organisation_committee_backup')
    op.drop_table(u'question_reply_backup')
    op.drop_table(u'qa_tmp')
    op.drop_table(u'tmp_organisation_committee')
    op.add_column('event', sa.Column('actual_end_time', sa.Time(timezone=True), nullable=True))
    op.add_column('event', sa.Column('actual_start_time', sa.Time(timezone=True), nullable=True))
    op.add_column('event', sa.Column('pmg_monitor', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'pmg_monitor')
    op.drop_column('event', 'actual_start_time')
    op.drop_column('event', 'actual_end_time')
    op.create_table(u'tmp_organisation_committee',
    sa.Column(u'domain', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column(u'committee', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table(u'qa_tmp',
    sa.Column(u'nid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column(u'body', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table(u'question_reply_backup',
    sa.Column(u'id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'committee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column(u'start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column(u'body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column(u'question_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column(u'nid', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table(u'organisation_committee_backup',
    sa.Column(u'organisation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'committee_id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_table('committee_meeting_attendance')
    ### end Alembic commands ###
