"""Drop rich_text table

Revision ID: 1bc74869f9f0
Revises: 122a38429a58
Create Date: 2015-02-10 15:43:11.651364

"""

# revision identifiers, used by Alembic.
revision = '1bc74869f9f0'
down_revision = '122a38429a58'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_content_rich_text_id', table_name='content')
    op.drop_constraint(u'content_rich_text_id_fkey', 'content', type_='foreignkey')
    op.drop_column('content', u'rich_text_id')
    op.drop_table(u'rich_text')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column(u'rich_text_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'content_rich_text_id_fkey', 'content', u'rich_text', [u'rich_text_id'], [u'id'])
    op.create_index(u'ix_content_rich_text_id', 'content', [u'rich_text_id'], unique=False)
    op.create_table(u'rich_text',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column(u'summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id', name=u'rich_text_pkey')
    )
    ### end Alembic commands ###
