"""remove_content_table

Revision ID: 1dd2771cbf39
Revises: 36978dc8dacf
Create Date: 2015-03-20 09:51:40.344639

"""

# revision identifiers, used by Alembic.
revision = '1dd2771cbf39'
down_revision = '36978dc8dacf'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("alter table content rename to old_content")
    #op.drop_table(u'content')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("alter table old_content rename to content")
    #op.create_table(u'content',
    #sa.Column(u'id', sa.INTEGER(), nullable=False),
    #sa.Column(u'type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    #sa.Column(u'event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.Column(u'file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.Column(u'body', sa.TEXT(), autoincrement=False, nullable=True),
    #sa.Column(u'summary', sa.TEXT(), autoincrement=False, nullable=True),
    #sa.ForeignKeyConstraint([u'event_id'], [u'event.id'], name=u'content_event_id_fkey'),
    #sa.ForeignKeyConstraint([u'file_id'], [u'file.id'], name=u'content_file_id_fkey'),
    #sa.PrimaryKeyConstraint(u'id', name=u'content_pkey')
    #)
    ### end Alembic commands ###
