"""file_path not null

Revision ID: 22a98e52027d
Revises: b432bbc7598
Create Date: 2015-03-29 16:00:47.357808

"""

# revision identifiers, used by Alembic.
revision = '22a98e52027d'
down_revision = 'b432bbc7598'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###
