"""event_body_summary

Revision ID: 28cc6044e27f
Revises: 4037703104ea
Create Date: 2015-03-17 10:49:27.400016

"""

# revision identifiers, used by Alembic.
revision = '28cc6044e27f'
down_revision = '4037703104ea'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("delete from content where event_id is null")
    op.add_column('event', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('event', sa.Column('summary', sa.Text(), nullable=True))
    op.execute("""
        update event
        set body = c.body, summary = c.summary
        from content c
        where c.type in ('hansard', 'briefing', 'committee-meeting-report')
        and event.id = c.event_id
        """)
    # op.execute("delete from content where type in ('hansard', 'briefing', 'committee-meeting-report')")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'summary')
    op.drop_column('event', 'body')
    ### end Alembic commands ###
