"""committee_question_attachments

Revision ID: 2c6a08d9cdef
Revises: 2530c2d31010
Create Date: 2015-07-15 15:14:50.022602

"""

# revision identifiers, used by Alembic.
revision = '2c6a08d9cdef'
down_revision = '2530c2d31010'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee_question_file_join',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_question_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['committee_question_id'], ['committee_question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_committee_question_file_join_committee_question_id', 'committee_question_file_join', ['committee_question_id'], unique=False)
    op.create_index(u'ix_committee_question_file_join_file_id', 'committee_question_file_join', ['file_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_committee_question_file_join_file_id', table_name='committee_question_file_join')
    op.drop_index(u'ix_committee_question_file_join_committee_question_id', table_name='committee_question_file_join')
    op.drop_table('committee_question_file_join')
    ### end Alembic commands ###
