"""event title required

Revision ID: 304c3434c2f9
Revises: 28cc6044e27f
Create Date: 2015-03-17 11:24:11.302424

"""

# revision identifiers, used by Alembic.
revision = '304c3434c2f9'
down_revision = '28cc6044e27f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'title',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'title',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    ### end Alembic commands ###
