"""event date is required

Revision ID: 32c9bf9a1bd8
Revises: 3b3a939bf12c
Create Date: 2015-02-11 15:14:35.608729

"""

# revision identifiers, used by Alembic.
revision = '32c9bf9a1bd8'
down_revision = '3b3a939bf12c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    ### end Alembic commands ###
