"""Add not-null constraints on membership table.

Revision ID: 33ad6ad8f955
Revises: 4c3554286996
Create Date: 2015-01-30 19:17:13.409798

"""

# revision identifiers, used by Alembic.
revision = '33ad6ad8f955'
down_revision = '4c3554286996'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('committee_members', 'committee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('committee_members', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('committee_members', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('committee_members', 'committee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
