"""User email can't be null

Revision ID: 349371b86798
Revises: 30b25dd39af0
Create Date: 2015-02-16 10:17:27.349463

"""

# revision identifiers, used by Alembic.
revision = '349371b86798'
down_revision = '30b25dd39af0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text(u"''"),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###
