"""tabled_committee_report_files

Revision ID: 36978dc8dacf
Revises: 4d5eb029f9cc
Create Date: 2015-03-18 09:21:11.757224

"""

# revision identifiers, used by Alembic.
revision = '36978dc8dacf'
down_revision = '4d5eb029f9cc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE tabled_committee_report_file_join ADD COLUMN id SERIAL')
    op.alter_column('tabled_committee_report_file_join', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tabled_committee_report_file_join', 'tabled_committee_report_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(u'ix_tabled_committee_report_file_join_file_id', 'tabled_committee_report_file_join', ['file_id'], unique=False)
    op.create_index(u'ix_tabled_committee_report_file_join_tabled_committee_report_id', 'tabled_committee_report_file_join', ['tabled_committee_report_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_tabled_committee_report_file_join_tabled_committee_report_id', table_name='tabled_committee_report_file_join')
    op.drop_index(u'ix_tabled_committee_report_file_join_file_id', table_name='tabled_committee_report_file_join')
    op.alter_column('tabled_committee_report_file_join', 'tabled_committee_report_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tabled_committee_report_file_join', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tabled_committee_report_file_join', 'id')
    ### end Alembic commands ###
