"""public_participation

Revision ID: 388733668ba7
Revises: 3969d67f5cb6
Create Date: 2015-03-09 15:14:14.453202

"""

# revision identifiers, used by Alembic.
revision = '388733668ba7'
down_revision = '3969d67f5cb6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('public_participation', sa.Boolean(), server_default=sa.text(u'false'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'public_participation')
    ### end Alembic commands ###
