"""remove redundant user subscription fields

Revision ID: 3fc4c97dc6bd
Revises: 3d723944025f
Create Date: 2015-01-27 18:11:15.822193

"""

# revision identifiers, used by Alembic.
revision = '3fc4c97dc6bd'
down_revision = '3d723944025f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', u'subscribe_bill')
    op.drop_column('user', u'subscribe_call_for_comment')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(u'subscribe_call_for_comment', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column(u'subscribe_bill', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
