"""Add premium subscription for users

Revision ID: 414f1f4508c
Revises: 5884915e5b9e
Create Date: 2015-01-29 16:34:49.574415

"""

# revision identifiers, used by Alembic.
revision = '414f1f4508c'
down_revision = '5884915e5b9e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_committee',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_committee')
    ### end Alembic commands ###
