"""mp_current

Revision ID: 460ef2ec2d21
Revises: 32d14f5f9773
Create Date: 2015-02-06 08:02:52.350474

"""

# revision identifiers, used by Alembic.
revision = '460ef2ec2d21'
down_revision = '32d14f5f9773'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('current', sa.Boolean(), server_default=sa.text(u'true'), nullable=False))
    op.create_index(u'ix_member_current', 'member', ['current'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_member_current', table_name='member')
    op.drop_column('member', 'current')
    ### end Alembic commands ###
