"""Allow events to be featured.

Revision ID: 46b85e11f48f
Revises: 813335b894b
Create Date: 2015-02-12 14:33:54.637510

"""

# revision identifiers, used by Alembic.
revision = '46b85e11f48f'
down_revision = '813335b894b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('featured', sa.Boolean(), server_default=sa.text(u'false'), nullable=False))
    op.create_index(u'ix_event_featured', 'event', ['featured'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_event_featured', table_name='event')
    op.drop_column('event', 'featured')
    ### end Alembic commands ###
