"""committee_defaults

Revision ID: 4c7e8d899149
Revises: 1528c8a3c46e
Create Date: 2015-03-17 09:48:14.966818

"""

# revision identifiers, used by Alembic.
revision = '4c7e8d899149'
down_revision = '1528c8a3c46e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE committee SET ad_hoc = false where ad_hoc IS NULL")
    op.alter_column('committee', 'ad_hoc',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.execute("UPDATE committee SET premium = false where premium IS NULL")
    op.alter_column('committee', 'premium',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('committee', 'premium',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('committee', 'ad_hoc',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    ### end Alembic commands ###
