"""Add nid fields where needed.

Revision ID: 516aebc76ca8
Revises: 4bd2c7b6ed8a
Create Date: 2015-01-30 10:30:52.125390

"""

# revision identifiers, used by Alembic.
revision = '516aebc76ca8'
down_revision = '4bd2c7b6ed8a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('nid', sa.Integer(), nullable=True))
    op.add_column('question_reply', sa.Column('nid', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_reply', 'nid')
    op.drop_column('event', 'nid')
    ### end Alembic commands ###
