"""create BillVersion model

Revision ID: 813335b894b
Revises: 3d31ea243165
Create Date: 2015-02-12 12:19:44.061001

"""

# revision identifiers, used by Alembic.
revision = '813335b894b'
down_revision = '3d31ea243165'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_files')

    op.create_table('bill_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_versions')
    ### end Alembic commands ###
