"""user_expiry

Revision ID: a91338ba772
Revises: 460ef2ec2d21
Create Date: 2015-02-06 08:29:52.279938

"""

# revision identifiers, used by Alembic.
revision = 'a91338ba772'
down_revision = '460ef2ec2d21'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organisation', 'expiry',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=True)
    op.add_column('user', sa.Column('expiry', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'expiry')
    op.alter_column('organisation', 'expiry',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    ### end Alembic commands ###
