"""Petitions

Revision ID: 10c470ccc29
Revises: 46fa8a10011
Create Date: 2025-06-22 09:35:55.200748

"""

# revision identifiers, used by Alembic.
revision = '10c470ccc29'
down_revision = '46fa8a10011'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petition_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_petition_status')),
    sa.UniqueConstraint('name', name=op.f('petition_status_name_key'))
    )
    op.add_column('petition', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_petition_status_id_petition_status'), 'petition', 'petition_status', ['status_id'], ['id'])
    op.drop_column('petition', 'status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petition', sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_petition_status_id_petition_status'), 'petition', type_='foreignkey')
    op.drop_column('petition', 'status_id')
    op.drop_table('petition_status')
    ### end Alembic commands ###
