"""timestamps

Revision ID: 12ce767acbcf
Revises: bb8e91317dc
Create Date: 2015-10-07 09:30:30.526861

"""

# revision identifiers, used by Alembic.
revision = '12ce767acbcf'
down_revision = 'bb8e91317dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('bill', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.create_index(op.f('ix_bill_created_at'), 'bill', ['created_at'], unique=False)
    op.create_index(op.f('ix_bill_updated_at'), 'bill', ['updated_at'], unique=False)
    op.add_column('call_for_comment', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('call_for_comment', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.create_index(op.f('ix_call_for_comment_created_at'), 'call_for_comment', ['created_at'], unique=False)
    op.create_index(op.f('ix_call_for_comment_updated_at'), 'call_for_comment', ['updated_at'], unique=False)
    op.execute("COMMIT")

    op.add_column('committee', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('committee', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.create_index(op.f('ix_committee_created_at'), 'committee', ['created_at'], unique=False)
    op.create_index(op.f('ix_committee_updated_at'), 'committee', ['updated_at'], unique=False)
    op.add_column('committee_meeting_attendance', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('committee_meeting_attendance', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.create_index(op.f('ix_committee_meeting_attendance_created_at'), 'committee_meeting_attendance', ['created_at'], unique=False)
    op.create_index(op.f('ix_committee_meeting_attendance_updated_at'), 'committee_meeting_attendance', ['updated_at'], unique=False)
    op.add_column('committee_question', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('committee_question', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.create_index(op.f('ix_committee_question_created_at'), 'committee_question', ['created_at'], unique=False)
    op.create_index(op.f('ix_committee_question_updated_at'), 'committee_question', ['updated_at'], unique=False)
    op.add_column('daily_schedule', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('daily_schedule', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.create_index(op.f('ix_daily_schedule_created_at'), 'daily_schedule', ['created_at'], unique=False)
    op.create_index(op.f('ix_daily_schedule_updated_at'), 'daily_schedule', ['updated_at'], unique=False)
    op.execute("COMMIT")

    op.add_column('event', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('event', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.create_index(op.f('ix_event_created_at'), 'event', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_updated_at'), 'event', ['updated_at'], unique=False)
    op.execute("COMMIT")

    op.add_column('gazette', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('gazette', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.create_index(op.f('ix_gazette_created_at'), 'gazette', ['created_at'], unique=False)
    op.create_index(op.f('ix_gazette_updated_at'), 'gazette', ['updated_at'], unique=False)
    op.add_column('member', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('member', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.create_index(op.f('ix_member_created_at'), 'member', ['created_at'], unique=False)
    op.create_index(op.f('ix_member_updated_at'), 'member', ['updated_at'], unique=False)
    op.add_column('minister', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('minister', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.create_index(op.f('ix_minister_created_at'), 'minister', ['created_at'], unique=False)
    op.create_index(op.f('ix_minister_updated_at'), 'minister', ['updated_at'], unique=False)
    op.execute("COMMIT")

    op.add_column('policy_document', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('policy_document', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.create_index(op.f('ix_policy_document_created_at'), 'policy_document', ['created_at'], unique=False)
    op.create_index(op.f('ix_policy_document_updated_at'), 'policy_document', ['updated_at'], unique=False)
    op.add_column('question_reply', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('question_reply', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.create_index(op.f('ix_question_reply_created_at'), 'question_reply', ['created_at'], unique=False)
    op.create_index(op.f('ix_question_reply_updated_at'), 'question_reply', ['updated_at'], unique=False)
    op.add_column('schedule', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('schedule', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.create_index(op.f('ix_schedule_created_at'), 'schedule', ['created_at'], unique=False)
    op.create_index(op.f('ix_schedule_updated_at'), 'schedule', ['updated_at'], unique=False)
    op.add_column('tabled_committee_report', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('tabled_committee_report', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.create_index(op.f('ix_tabled_committee_report_created_at'), 'tabled_committee_report', ['created_at'], unique=False)
    op.create_index(op.f('ix_tabled_committee_report_updated_at'), 'tabled_committee_report', ['updated_at'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tabled_committee_report_updated_at'), table_name='tabled_committee_report')
    op.drop_index(op.f('ix_tabled_committee_report_created_at'), table_name='tabled_committee_report')
    op.drop_column('tabled_committee_report', 'updated_at')
    op.drop_column('tabled_committee_report', 'created_at')
    op.drop_index(op.f('ix_schedule_updated_at'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_created_at'), table_name='schedule')
    op.drop_column('schedule', 'updated_at')
    op.drop_column('schedule', 'created_at')
    op.drop_index(op.f('ix_question_reply_updated_at'), table_name='question_reply')
    op.drop_index(op.f('ix_question_reply_created_at'), table_name='question_reply')
    op.drop_column('question_reply', 'updated_at')
    op.drop_column('question_reply', 'created_at')
    op.drop_index(op.f('ix_policy_document_updated_at'), table_name='policy_document')
    op.drop_index(op.f('ix_policy_document_created_at'), table_name='policy_document')
    op.drop_column('policy_document', 'updated_at')
    op.drop_column('policy_document', 'created_at')
    op.drop_index(op.f('ix_minister_updated_at'), table_name='minister')
    op.drop_index(op.f('ix_minister_created_at'), table_name='minister')
    op.drop_column('minister', 'updated_at')
    op.drop_column('minister', 'created_at')
    op.drop_index(op.f('ix_member_updated_at'), table_name='member')
    op.drop_index(op.f('ix_member_created_at'), table_name='member')
    op.drop_column('member', 'updated_at')
    op.drop_column('member', 'created_at')
    op.drop_index(op.f('ix_gazette_updated_at'), table_name='gazette')
    op.drop_index(op.f('ix_gazette_created_at'), table_name='gazette')
    op.drop_column('gazette', 'updated_at')
    op.drop_column('gazette', 'created_at')
    op.drop_index(op.f('ix_event_updated_at'), table_name='event')
    op.drop_index(op.f('ix_event_created_at'), table_name='event')
    op.drop_column('event', 'updated_at')
    op.drop_column('event', 'created_at')
    op.drop_index(op.f('ix_daily_schedule_updated_at'), table_name='daily_schedule')
    op.drop_index(op.f('ix_daily_schedule_created_at'), table_name='daily_schedule')
    op.drop_column('daily_schedule', 'updated_at')
    op.drop_column('daily_schedule', 'created_at')
    op.drop_index(op.f('ix_committee_question_updated_at'), table_name='committee_question')
    op.drop_index(op.f('ix_committee_question_created_at'), table_name='committee_question')
    op.drop_column('committee_question', 'updated_at')
    op.drop_column('committee_question', 'created_at')
    op.drop_index(op.f('ix_committee_meeting_attendance_updated_at'), table_name='committee_meeting_attendance')
    op.drop_index(op.f('ix_committee_meeting_attendance_created_at'), table_name='committee_meeting_attendance')
    op.drop_column('committee_meeting_attendance', 'updated_at')
    op.drop_column('committee_meeting_attendance', 'created_at')
    op.drop_index(op.f('ix_committee_updated_at'), table_name='committee')
    op.drop_index(op.f('ix_committee_created_at'), table_name='committee')
    op.drop_column('committee', 'updated_at')
    op.drop_column('committee', 'created_at')
    op.drop_index(op.f('ix_call_for_comment_updated_at'), table_name='call_for_comment')
    op.drop_index(op.f('ix_call_for_comment_created_at'), table_name='call_for_comment')
    op.drop_column('call_for_comment', 'updated_at')
    op.drop_column('call_for_comment', 'created_at')
    op.drop_index(op.f('ix_bill_updated_at'), table_name='bill')
    op.drop_index(op.f('ix_bill_created_at'), table_name='bill')
    op.drop_column('bill', 'updated_at')
    op.drop_column('bill', 'created_at')
    ### end Alembic commands ###
