"""Add 'is_premium' field to Committee model.

Revision ID: 148ca74a6d3
Revises: 544fa615efc3
Create Date: 2015-01-22 13:29:13.208791

"""

# revision identifiers, used by Alembic.
revision = '148ca74a6d3'
down_revision = '544fa615efc3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('committee', sa.Column('premium', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('committee', 'premium')
    ### end Alembic commands ###
