"""cte-last-active-year

Revision ID: 14b8fbcc1386
Revises: 39f25296cd6
Create Date: 2017-07-04 12:39:57.873173

"""

# revision identifiers, used by Alembic.
revision = '14b8fbcc1386'
down_revision = '39f25296cd6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('committee', sa.Column('last_active_year', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('committee', 'last_active_year')
    ### end Alembic commands ###
