"""call_for_comment_required_fields

Revision ID: 1528c8a3c46e
Revises: 2a5b2b63d3e5
Create Date: 2015-03-16 15:39:34.113154

"""

# revision identifiers, used by Alembic.
revision = '1528c8a3c46e'
down_revision = '2a5b2b63d3e5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call_for_comment', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('call_for_comment', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call_for_comment', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('call_for_comment', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    ### end Alembic commands ###
