"""petitions table changes

Revision ID: 163aa83c330
Revises: 1628ea2a5b6
Create Date: 2025-09-11 06:18:16.213875

"""

# revision identifiers, used by Alembic.
revision = '163aa83c330'
down_revision = '1628ea2a5b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petition_files',
    sa.Column('petition_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], name=op.f('fk_petition_files_file_id_file')),
    sa.ForeignKeyConstraint(['petition_id'], ['petition.id'], name=op.f('fk_petition_files_petition_id_petition')),
    sa.PrimaryKeyConstraint('petition_id', 'file_id', name=op.f('pk_petition_files'))
    )
    op.add_column('petition', sa.Column('petition_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_petition_petition_file_id_file'), 'petition', 'file', ['petition_file_id'], ['id'])
    op.add_column('petition_status', sa.Column('step', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petition_status', 'step')
    op.drop_constraint(op.f('fk_petition_petition_file_id_file'), 'petition', type_='foreignkey')
    op.drop_column('petition', 'petition_file_id')
    op.drop_table('petition_files')
    ### end Alembic commands ###
