"""Add petition events table

Revision ID: 1729ea3b7c8f
Revises: 1628ea2a5b6
Create Date: 2025-11-03 00:00:00.000000

"""

# revision identifiers, used by Alembic.
revision = '1729ea3b7c8f'
down_revision = '1628ea2a5b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('petition_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('petition_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], name=op.f('fk_petition_event_committee_id_committee'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['petition_id'], ['petition.id'], name=op.f('fk_petition_event_petition_id_petition'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['petition_status.id'], name=op.f('fk_petition_event_status_id_petition_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_petition_event'))
    )
    op.create_index(op.f('ix_petition_event_committee_id'), 'petition_event', ['committee_id'], unique=False)
    op.create_index(op.f('ix_petition_event_petition_id'), 'petition_event', ['petition_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_petition_event_petition_id'), table_name='petition_event')
    op.drop_index(op.f('ix_petition_event_committee_id'), table_name='petition_event')
    op.drop_table('petition_event')
    ### end Alembic commands ###