"""add date and featured fields to posts

Revision ID: 191f4dbb7278
Revises: 22a87ce63503
Create Date: 2017-08-17 14:22:51.287803

"""

# revision identifiers, used by Alembic.
revision = '191f4dbb7278'
down_revision = '22a87ce63503'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('post', sa.Column('featured', sa.Boolean(), server_default=sa.text(u'false'), nullable=False))
    op.create_index(op.f('ix_post_date'), 'post', ['date'], unique=False)
    op.create_index(op.f('ix_post_featured'), 'post', ['featured'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_featured'), table_name='post')
    op.drop_index(op.f('ix_post_date'), table_name='post')
    op.drop_column('post', 'featured')
    op.drop_column('post', 'date')
    ### end Alembic commands ###
