"""question_reply_files

Revision ID: 1c6a96c17073
Revises: 3a69784c209f
Create Date: 2015-06-23 14:16:27.140859

"""

# revision identifiers, used by Alembic.
revision = '1c6a96c17073'
down_revision = '3a69784c209f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_reply_file_join',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_reply_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_reply_id'], ['question_reply.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_question_reply_file_join_file_id', 'question_reply_file_join', ['file_id'], unique=False)
    op.create_index(u'ix_question_reply_file_join_question_reply_id', 'question_reply_file_join', ['question_reply_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_question_reply_file_join_question_reply_id', table_name='question_reply_file_join')
    op.drop_index(u'ix_question_reply_file_join_file_id', table_name='question_reply_file_join')
    op.drop_table('question_reply_file_join')
    ### end Alembic commands ###
