"""ministers

Revision ID: 1cda3dd1789
Revises: 985ba1ea25b
Create Date: 2015-09-03 11:55:28.066944

"""

# revision identifiers, used by Alembic.
revision = '1cda3dd1789'
down_revision = '985ba1ea25b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minister',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'committee', sa.Column('minister_id', sa.Integer(), nullable=True))
    op.create_foreign_key('committee_minister_id_fkey', 'committee', 'minister', ['minister_id'], ['id'], ondelete='SET NULL')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('committee_minister_id_fkey', 'committee', type_='foreignkey')
    op.drop_column(u'committee', 'minister_id')
    op.drop_table('minister')
    ### end Alembic commands ###
