"""Add index to user email.

Revision ID: 1db076d08d78
Revises: 4b73b02d9536
Create Date: 2015-01-19 17:34:30.214618

"""

# revision identifiers, used by Alembic.
revision = '1db076d08d78'
down_revision = '4b73b02d9536'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'hansard')
    op.drop_table(u'briefing_file_join')
    # op.drop_table(u'book')
    op.drop_table(u'featured_committee_meeting_join')
    op.drop_table(u'committee_info')
    op.drop_table(u'tabled_committee_report_committee_join')
    op.drop_table(u'book_file_join')
    op.drop_table(u'briefing')
    op.drop_table(u'featured_committee_meeting_report_join')
    op.drop_table(u'committee_meeting_report')
    op.create_index(u'ix_user_email', 'user', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_user_email', table_name='user')
    op.create_table(u'committee_meeting_report',
    sa.Column(u'id', sa.INTEGER(), server_default=sa.text(u"nextval('committee_meeting_report_id_seq'::regclass)"), nullable=False),
    sa.Column(u'body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column(u'summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column(u'event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id', name=u'committee_meeting_report_pkey')
    )
    op.create_table(u'featured_committee_meeting_report_join',
    sa.Column(u'featured_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'committee_meeting_report_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint([u'committee_meeting_report_id'], [u'committee_meeting_report.id'], name=u'featured_committee_meeting_rep_committee_meeting_report_id_fkey')
    )
    op.create_table(u'briefing',
    sa.Column(u'id', sa.INTEGER(), server_default=sa.text(u"nextval('briefing_id_seq'::regclass)"), nullable=False),
    sa.Column(u'title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column(u'briefing_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column(u'summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column(u'minutes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column(u'presentation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column(u'start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id', name=u'briefing_pkey')
    )
    op.create_table(u'book_file_join',
    sa.Column(u'book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint([u'book_id'], [u'book.id'], name=u'book_file_join_book_id_fkey')
    )
    op.create_table(u'tabled_committee_report_committee_join',
    sa.Column(u'tabled_committee_report_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'committee_id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table(u'committee_info',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'about', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column(u'contact_details', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.Column(u'organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint(u'id', name=u'committee_info_pkey')
    )
    op.create_table(u'featured_committee_meeting_join',
    sa.Column(u'featured_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'committee_meeting_id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table(u'briefing_file_join',
    sa.Column(u'briefing_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint([u'briefing_id'], [u'briefing.id'], name=u'briefing_file_join_briefing_id_fkey')
    )
    op.create_table(u'book',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column(u'summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column(u'body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column(u'start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column(u'nid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id', name=u'book_pkey')
    )
    op.create_table(u'hansard',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column(u'meeting_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column(u'start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column(u'body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id', name=u'hansard_pkey')
    )
    ### end Alembic commands ###
