"""Added user following relation to user

Revision ID: 1e3be3ff186d
Revises: 29918969a90
Create Date: 2016-10-24 13:02:49.915605

"""

# revision identifiers, used by Alembic.
revision = '1e3be3ff186d'
down_revision = '29918969a90'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_following',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], name=op.f('fk_user_following_committee_id_committee'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_following_user_id_user'), ondelete='CASCADE')
    )
    op.create_index(op.f('ix_user_following_created_at'), 'user_following', ['created_at'], unique=False)
    op.execute('insert into user_following select * from user_committee_alerts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_following_created_at'), table_name='user_following')
    op.drop_table('user_following')
    ### end Alembic commands ###
