"""Add contact_details to House

Revision ID: 1f97f799a477
Revises: 2df9ce70bad
Create Date: 2018-08-08 10:58:44.869939

"""

# revision identifiers, used by Alembic.
revision = '1f97f799a477'
down_revision = '2df9ce70bad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('contact_details', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('house', 'contact_details')
    ### end Alembic commands ###
