"""Multiple files per post is easier copy pasta

Revision ID: 22a87ce63503
Revises: 4dfdaa23de0
Create Date: 2017-08-17 14:12:47.484638

"""

# revision identifiers, used by Alembic.
revision = '22a87ce63503'
down_revision = '4dfdaa23de0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], name=op.f('fk_post_files_file_id_file'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_post_files_post_id_post'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_files'))
    )
    op.create_index(op.f('ix_post_files_file_id'), 'post_files', ['file_id'], unique=False)
    op.create_index(op.f('ix_post_files_post_id'), 'post_files', ['post_id'], unique=False)
    op.drop_index('ix_post_featured_image_id', table_name='post')
    op.drop_constraint(u'fk_post_featured_image_id_file', 'post', type_='foreignkey')
    op.drop_column(u'post', 'featured_image_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'post', sa.Column('featured_image_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'fk_post_featured_image_id_file', 'post', 'file', ['featured_image_id'], ['id'], ondelete=u'CASCADE')
    op.create_index('ix_post_featured_image_id', 'post', ['featured_image_id'], unique=False)
    op.drop_index(op.f('ix_post_files_post_id'), table_name='post_files')
    op.drop_index(op.f('ix_post_files_file_id'), table_name='post_files')
    op.drop_table('post_files')
    ### end Alembic commands ###
