"""empty message

Revision ID: 248d10b76bb
Revises: 34fdf9d2b1f
Create Date: 2026-01-09 13:07:24.891732

"""

# revision identifiers, used by Alembic.
revision = '248d10b76bb'
down_revision = '34fdf9d2b1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petition_event', sa.Column('committee_report_id', sa.Integer(), nullable=True))
    op.alter_column('petition_event', 'system_generated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_petition_event_committee_report_id'), 'petition_event', ['committee_report_id'], unique=False)
    op.create_foreign_key(op.f('fk_petition_event_committee_report_id_tabled_committee_report'), 'petition_event', 'tabled_committee_report', ['committee_report_id'], ['id'], ondelete='SET NULL')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_petition_event_committee_report_id_tabled_committee_report'), 'petition_event', type_='foreignkey')
    op.drop_index(op.f('ix_petition_event_committee_report_id'), table_name='petition_event')
    op.alter_column('petition_event', 'system_generated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('petition_event', 'committee_report_id')
    ### end Alembic commands ###
