"""committee_questions

Revision ID: 2530c2d31010
Revises: 1c6a96c17073
Create Date: 2015-07-15 14:10:33.199667

"""

# revision identifiers, used by Alembic.
revision = '2530c2d31010'
down_revision = '1c6a96c17073'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('written_number', sa.Integer(), nullable=True),
    sa.Column('oral_number', sa.Integer(), nullable=True),
    sa.Column('president_number', sa.Integer(), nullable=True),
    sa.Column('deputy_president_number', sa.Integer(), nullable=True),
    sa.Column('answer_type', sa.Enum('oral', 'written', name='committee_question_answer_type_enum'), nullable=False),
    sa.Column('answered_on', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('question_to_name', sa.String(length=1024), nullable=False),
    sa.Column('translated', sa.Boolean(), nullable=False),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('asked_by_name', sa.String(length=1024), nullable=False),
    sa.Column('asked_by_member_id', sa.Integer(), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asked_by_member_id'], ['member.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['file.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_committee_question_code', 'committee_question', ['code'], unique=True)
    op.create_index(u'ix_committee_question_deputy_president_number', 'committee_question', ['deputy_president_number'], unique=False)
    op.create_index(u'ix_committee_question_oral_number', 'committee_question', ['oral_number'], unique=False)
    op.create_index(u'ix_committee_question_president_number', 'committee_question', ['president_number'], unique=False)
    op.create_index(u'ix_committee_question_question_number', 'committee_question', ['question_number'], unique=False)
    op.create_index(u'ix_committee_question_source_file_id', 'committee_question', ['source_file_id'], unique=False)
    op.create_index(u'ix_committee_question_written_number', 'committee_question', ['written_number'], unique=False)
    op.create_index(u'ix_committee_question_year', 'committee_question', ['year'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_committee_question_year', table_name='committee_question')
    op.drop_index(u'ix_committee_question_written_number', table_name='committee_question')
    op.drop_index(u'ix_committee_question_source_file_id', table_name='committee_question')
    op.drop_index(u'ix_committee_question_question_number', table_name='committee_question')
    op.drop_index(u'ix_committee_question_president_number', table_name='committee_question')
    op.drop_index(u'ix_committee_question_oral_number', table_name='committee_question')
    op.drop_index(u'ix_committee_question_deputy_president_number', table_name='committee_question')
    op.drop_index(u'ix_committee_question_code', table_name='committee_question')
    op.drop_table('committee_question')
    op.execute('drop type committee_question_answer_type_enum')
    ### end Alembic commands ###
