"""house-speaker

Revision ID: 270efdf57cc
Revises: 5e88e38a231
Create Date: 2018-11-26 11:09:47.664806

"""

# revision identifiers, used by Alembic.
revision = '270efdf57cc'
down_revision = '5e88e38a231'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('speaker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_house_speaker_id_member'), 'house', 'member', ['speaker_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_house_speaker_id_member'), 'house', type_='foreignkey')
    op.drop_column('house', 'speaker_id')
    ### end Alembic commands ###
