"""wider_event_title

Revision ID: 2a5b2b63d3e5
Revises: 388733668ba7
Create Date: 2015-03-09 16:30:48.473784

"""

# revision identifiers, used by Alembic.
revision = '2a5b2b63d3e5'
down_revision = '388733668ba7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'title',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=1024),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'title',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    ### end Alembic commands ###
