"""page-files

Revision ID: 2c5f5b0bbd94
Revises: 22a98e52027d
Create Date: 2015-03-30 11:48:46.483395

"""

# revision identifiers, used by Alembic.
revision = '2c5f5b0bbd94'
down_revision = '22a98e52027d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_page_files_file_id', 'page_files', ['file_id'], unique=False)
    op.create_index(u'ix_page_files_page_id', 'page_files', ['page_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_page_files_page_id', table_name='page_files')
    op.drop_index(u'ix_page_files_file_id', table_name='page_files')
    op.drop_table('page_files')
    ### end Alembic commands ###
