"""daily schedule updates

Revision ID: 2df9ce70bad
Revises: 376804c871b4
Create Date: 2018-03-14 12:30:40.844228

"""

# revision identifiers, used by Alembic.
revision = '2df9ce70bad'
down_revision = '376804c871b4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_house_join')
    op.drop_table('schedule')
    # NCOP by default for existing entries
    op.add_column('daily_schedule', sa.Column('house_id', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('daily_schedule', 'house_id', server_default=None)
    # remove default
    op.alter_column('daily_schedule', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index(op.f('ix_daily_schedule_house_id'), 'daily_schedule', ['house_id'], unique=False)
    op.create_foreign_key(op.f('fk_daily_schedule_house_id_house'), 'daily_schedule', 'house', ['house_id'], ['id'])
    op.drop_column('daily_schedule', 'schedule_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_schedule', sa.Column('schedule_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_daily_schedule_house_id_house'), 'daily_schedule', type_='foreignkey')
    op.drop_index(op.f('ix_daily_schedule_house_id'), table_name='daily_schedule')
    op.alter_column('daily_schedule', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('daily_schedule', 'house_id')

    op.create_table('schedule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meeting_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('meeting_time', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'schedule_pkey')
    )
    ### end Alembic commands ###
    op.create_table('schedule_house_join',
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('house_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['house_id'], [u'house.id'], name=u'schedule_house_join_house_id_fkey'),
    sa.ForeignKeyConstraint(['schedule_id'], [u'schedule.id'], name=u'schedule_house_join_schedule_id_fkey')
    )
