"""drop unused bill_event_table

Revision ID: 2ff6718f2a66
Revises: 1bc74869f9f0
Create Date: 2015-02-11 09:28:12.315901

"""

# revision identifiers, used by Alembic.
revision = '2ff6718f2a66'
down_revision = '1bc74869f9f0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'bill_event')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'bill_event',
    sa.Column(u'event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'bill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint([u'bill_id'], [u'bill.id'], name=u'bill_event_bill_id_fkey'),
    sa.ForeignKeyConstraint([u'event_id'], [u'event.id'], name=u'bill_event_event_id_fkey')
    )
    ### end Alembic commands ###
