"""pa link unique

Revision ID: 3101ec185bdf
Revises: 51dd553fdf8b
Create Date: 2015-11-11 08:17:53.589389

"""

# revision identifiers, used by Alembic.
revision = '3101ec185bdf'
down_revision = '51dd553fdf8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('member_pa_link_key'), 'member', ['pa_link'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('member_pa_link_key'), 'member', type_='unique')
    ### end Alembic commands ###
