"""Petitions description

Revision ID: 3118156286b
Revises: 10c470ccc29
Create Date: 2025-06-22 10:07:04.998587

"""

# revision identifiers, used by Alembic.
revision = '3118156286b'
down_revision = '10c470ccc29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petition', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petition', 'description')
    ### end Alembic commands ###
