"""Add SoundcloudTrack model

Revision ID: 3160b5df63b4
Revises: 8cbc3d8dd55
Create Date: 2016-08-31 11:29:40.489495

"""

# revision identifiers, used by Alembic.
revision = '3160b5df63b4'
down_revision = '8cbc3d8dd55'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soundcloud_track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], name=op.f('fk_soundcloud_track_file_id_file'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_soundcloud_track'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soundcloud_track')
    ### end Alembic commands ###
