"""widen_file_mime

Revision ID: 32d14f5f9773
Revises: 206b2f94188c
Create Date: 2015-02-06 07:32:05.105459

"""

# revision identifiers, used by Alembic.
revision = '32d14f5f9773'
down_revision = '206b2f94188c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'file_mime',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'file_mime',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    ### end Alembic commands ###
