"""Add scheduled_start_time and actual_end_time to CommitteeMeeting

Revision ID: 33e499db410
Revises: e02ab1542a
Create Date: 2024-07-15 09:38:43.690415

"""

# revision identifiers, used by Alembic.
revision = '33e499db410'
down_revision = 'e02ab1542a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('scheduled_end_time', sa.Time(timezone=True), nullable=True))
    op.add_column('event', sa.Column('scheduled_start_time', sa.Time(timezone=True), nullable=True))
    op.alter_column('user', 'fs_uniquifier',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'fs_uniquifier',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.drop_column('event', 'scheduled_start_time')
    op.drop_column('event', 'scheduled_end_time')
    ### end Alembic commands ###
