"""empty message

Revision ID: 34fdf9d2b1f
Revises: 1337c883f34
Create Date: 2025-11-17 08:31:10.980763

"""

# revision identifiers, used by Alembic.
revision = '34fdf9d2b1f'
down_revision = '1337c883f34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petition_event', sa.Column('system_generated', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petition_event', 'system_generated')
    ### end Alembic commands ###
