"""attendence indexes

Revision ID: 3559c36f279d
Revises: 3daa1030c816
Create Date: 2015-07-21 09:34:59.716931

"""

# revision identifiers, used by Alembic.
revision = '3559c36f279d'
down_revision = '3daa1030c816'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('meeting_member_ix', 'committee_meeting_attendance', ['meeting_id', 'member_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('meeting_member_ix', table_name='committee_meeting_attendance')
    ### end Alembic commands ###
