"""empty message

Revision ID: 35d477d67b7
Revises: 33e499db410
Create Date: 2024-12-06 10:16:54.464973

"""

# revision identifiers, used by Alembic.
revision = '35d477d67b7'
down_revision = '33e499db410'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], name=op.f('fk_bill_file_bill_id_bill')),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], name=op.f('fk_bill_file_file_id_file')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_file'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_file')
    ### end Alembic commands ###
