"""empty message

Revision ID: 36b1d3045cb8
Revises: None
Create Date: 2019-07-15 16:42:37.795156

"""

# revision identifiers, used by Alembic.
revision = "36b1d3045cb8"
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bill_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bill_status")),
        sa.UniqueConstraint("name", name=op.f("bill_status_name_key")),
    )
    op.create_table(
        "bill_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("prefix", sa.String(length=5), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bill_type")),
        sa.UniqueConstraint("name", name=op.f("bill_type_name_key")),
    )
    op.create_table(
        "call_for_comment",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("committee_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("nid", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["committee_id"],
            ["committee.id"],
            name=op.f("fk_call_for_comment_committee_id_committee"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_call_for_comment")),
    )
    op.create_index(
        op.f("ix_call_for_comment_created_at"),
        "call_for_comment",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_call_for_comment_updated_at"),
        "call_for_comment",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "committee",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("contact_details", sa.Text(), nullable=True),
        sa.Column(
            "ad_hoc", sa.Boolean(), server_default=sa.text(u"false"), nullable=False
        ),
        sa.Column(
            "premium", sa.Boolean(), server_default=sa.text(u"false"), nullable=False
        ),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text(u"true"), nullable=False
        ),
        sa.Column("last_active_year", sa.Integer(), nullable=True),
        sa.Column(
            "monitored", sa.Boolean(), server_default=sa.text(u"true"), nullable=False
        ),
        sa.Column("house_id", sa.Integer(), nullable=False),
        sa.Column("minister_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["house_id"], ["house.id"], name=op.f("fk_committee_house_id_house")
        ),
        sa.ForeignKeyConstraint(
            ["minister_id"],
            ["minister.id"],
            name=op.f("fk_committee_minister_id_minister"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_committee")),
        sa.UniqueConstraint("name", name=op.f("committee_name_key")),
    )
    op.create_index(
        op.f("ix_committee_created_at"), "committee", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_committee_updated_at"), "committee", ["updated_at"], unique=False
    )
    op.create_table(
        "committee_meeting_attendance",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "alternate_member",
            sa.Boolean(),
            server_default=sa.text(u"false"),
            nullable=False,
        ),
        sa.Column(
            "attendance",
            sa.Enum(
                "A",
                "AP",
                "DE",
                "L",
                "LDE",
                "P",
                "Y",
                "U",
                name="meeting_attendance_enum",
            ),
            nullable=False,
        ),
        sa.Column("chairperson", sa.Boolean(), nullable=False),
        sa.Column("meeting_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["event.id"],
            name=op.f("fk_committee_meeting_attendance_meeting_id_event"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["member.id"],
            name=op.f("fk_committee_meeting_attendance_member_id_member"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_committee_meeting_attendance")),
    )
    op.create_index(
        op.f("ix_committee_meeting_attendance_created_at"),
        "committee_meeting_attendance",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_committee_meeting_attendance_updated_at"),
        "committee_meeting_attendance",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        "meeting_member_ix",
        "committee_meeting_attendance",
        ["meeting_id", "member_id"],
        unique=True,
    )
    op.create_table(
        "committee_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=True),
        sa.Column("committee_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["committee_id"],
            ["committee.id"],
            name=op.f("fk_committee_members_committee_id_committee"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["member.id"],
            name=op.f("fk_committee_members_member_id_member"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["membership_type.id"],
            name=op.f("fk_committee_members_type_id_membership_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_committee_members")),
    )
    op.create_table(
        "committee_question",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("minister_id", sa.Integer(), nullable=True),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("question_number", sa.Integer(), nullable=True),
        sa.Column("house_id", sa.Integer(), nullable=True),
        sa.Column("written_number", sa.Integer(), nullable=True),
        sa.Column("oral_number", sa.Integer(), nullable=True),
        sa.Column("president_number", sa.Integer(), nullable=True),
        sa.Column("deputy_president_number", sa.Integer(), nullable=True),
        sa.Column(
            "answer_type",
            sa.Enum("oral", "written", name="committee_question_answer_type_enum"),
            nullable=False,
        ),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("question_to_name", sa.String(length=1024), nullable=True),
        sa.Column("translated", sa.Boolean(), nullable=False),
        sa.Column("intro", sa.Text(), nullable=True),
        sa.Column("asked_by_name", sa.String(length=1024), nullable=True),
        sa.Column("asked_by_member_id", sa.Integer(), nullable=True),
        sa.Column("source_file_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asked_by_member_id"],
            ["member.id"],
            name=op.f("fk_committee_question_asked_by_member_id_member"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["house.id"],
            name=op.f("fk_committee_question_house_id_house"),
        ),
        sa.ForeignKeyConstraint(
            ["minister_id"],
            ["minister.id"],
            name=op.f("fk_committee_question_minister_id_minister"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["file.id"],
            name=op.f("fk_committee_question_source_file_id_file"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_committee_question")),
        sa.UniqueConstraint("date", "code", name="date_code_ix"),
        sa.UniqueConstraint(
            "date",
            "house_id",
            "deputy_president_number",
            name="date_deputy_president_number_ix",
        ),
        sa.UniqueConstraint(
            "date", "house_id", "oral_number", name="date_oral_number_ix"
        ),
        sa.UniqueConstraint(
            "date", "house_id", "president_number", name="date_president_number_ix"
        ),
        sa.UniqueConstraint(
            "date", "house_id", "written_number", name="date_written_number_ix"
        ),
    )
    op.create_index(
        op.f("ix_committee_question_code"), "committee_question", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_committee_question_created_at"),
        "committee_question",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_committee_question_deputy_president_number"),
        "committee_question",
        ["deputy_president_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_committee_question_oral_number"),
        "committee_question",
        ["oral_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_committee_question_president_number"),
        "committee_question",
        ["president_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_committee_question_question_number"),
        "committee_question",
        ["question_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_committee_question_source_file_id"),
        "committee_question",
        ["source_file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_committee_question_updated_at"),
        "committee_question",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_committee_question_written_number"),
        "committee_question",
        ["written_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_committee_question_year"), "committee_question", ["year"], unique=False
    )
    op.create_table(
        "committee_question_file_join",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("committee_question_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["committee_question_id"],
            ["committee_question.id"],
            name=op.f(
                "fk_committee_question_file_join_committee_question_id_committee_question"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
            name=op.f("fk_committee_question_file_join_file_id_file"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_committee_question_file_join")),
    )
    op.create_index(
        op.f("ix_committee_question_file_join_committee_question_id"),
        "committee_question_file_join",
        ["committee_question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_committee_question_file_join_file_id"),
        "committee_question_file_join",
        ["file_id"],
        unique=False,
    )
    op.create_table(
        "daily_schedule",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("nid", sa.Integer(), nullable=True),
        sa.Column("house_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["house_id"], ["house.id"], name=op.f("fk_daily_schedule_house_id_house")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_schedule")),
    )
    op.create_index(
        op.f("ix_daily_schedule_created_at"),
        "daily_schedule",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_schedule_house_id"), "daily_schedule", ["house_id"], unique=False
    )
    op.create_index(
        op.f("ix_daily_schedule_updated_at"),
        "daily_schedule",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "daily_schedule_file_join",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("daily_schedule_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["daily_schedule_id"],
            ["daily_schedule.id"],
            name=op.f("fk_daily_schedule_file_join_daily_schedule_id_daily_schedule"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
            name=op.f("fk_daily_schedule_file_join_file_id_file"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_schedule_file_join")),
    )
    op.create_index(
        op.f("ix_daily_schedule_file_join_daily_schedule_id"),
        "daily_schedule_file_join",
        ["daily_schedule_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_schedule_file_join_file_id"),
        "daily_schedule_file_join",
        ["file_id"],
        unique=False,
    )
    op.create_table(
        "email_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("subject", sa.String(length=100), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_template")),
    )
    op.create_index(
        op.f("ix_email_template_created_at"),
        "email_template",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "event",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("nid", sa.Integer(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.Column("committee_id", sa.Integer(), nullable=True),
        sa.Column("house_id", sa.Integer(), nullable=True),
        sa.Column("chairperson", sa.String(length=256), nullable=True),
        sa.Column(
            "public_participation",
            sa.Boolean(),
            server_default=sa.text(u"false"),
            nullable=True,
        ),
        sa.Column(
            "featured", sa.Boolean(), server_default=sa.text(u"false"), nullable=False
        ),
        sa.Column("actual_start_time", sa.Time(timezone=True), nullable=True),
        sa.Column("actual_end_time", sa.Time(timezone=True), nullable=True),
        sa.Column("pmg_monitor", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["committee_id"],
            ["committee.id"],
            name=op.f("fk_event_committee_id_committee"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["house_id"], ["house.id"], name=op.f("fk_event_house_id_house")
        ),
        sa.ForeignKeyConstraint(
            ["member_id"], ["member.id"], name=op.f("fk_event_member_id_member")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event")),
    )
    op.create_index(
        op.f("ix_event_committee_id"), "event", ["committee_id"], unique=False
    )
    op.create_index(op.f("ix_event_created_at"), "event", ["created_at"], unique=False)
    op.create_index(op.f("ix_event_featured"), "event", ["featured"], unique=False)
    op.create_index(op.f("ix_event_house_id"), "event", ["house_id"], unique=False)
    op.create_index(op.f("ix_event_id"), "event", ["id"], unique=False)
    op.create_index(op.f("ix_event_member_id"), "event", ["member_id"], unique=False)
    op.create_index(op.f("ix_event_type"), "event", ["type"], unique=False)
    op.create_index(op.f("ix_event_updated_at"), "event", ["updated_at"], unique=False)
    op.create_table(
        "event_bills",
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("bill_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill.id"],
            name=op.f("fk_event_bills_bill_id_bill"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
            name=op.f("fk_event_bills_event_id_event"),
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "event_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.id"],
            name=op.f("fk_event_files_event_id_event"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
            name=op.f("fk_event_files_file_id_file"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_files")),
    )
    op.create_index(
        op.f("ix_event_files_event_id"), "event_files", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_event_files_file_id"), "event_files", ["file_id"], unique=False
    )
    op.create_index(op.f("ix_event_files_id"), "event_files", ["id"], unique=False)
    op.create_table(
        "featured",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("blurb", sa.Text(), nullable=True),
        sa.Column("link", sa.String(length=255), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_featured")),
    )
    op.create_table(
        "file",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=True),
        sa.Column("file_mime", sa.String(length=100), nullable=True),
        sa.Column("file_path", sa.String(length=255), nullable=False),
        sa.Column("file_bytes", sa.BigInteger(), nullable=True),
        sa.Column("origname", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("playtime", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file")),
    )
    op.create_table(
        "gazette",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("nid", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gazette")),
    )
    op.create_index(
        op.f("ix_gazette_created_at"), "gazette", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_gazette_updated_at"), "gazette", ["updated_at"], unique=False
    )
    op.create_table(
        "gazette_file_join",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gazette_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
            name=op.f("fk_gazette_file_join_file_id_file"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["gazette_id"],
            ["gazette.id"],
            name=op.f("fk_gazette_file_join_gazette_id_gazette"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gazette_file_join")),
    )
    op.create_index(
        op.f("ix_gazette_file_join_file_id"),
        "gazette_file_join",
        ["file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gazette_file_join_gazette_id"),
        "gazette_file_join",
        ["gazette_id"],
        unique=False,
    )
    op.create_table(
        "member",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("profile_pic_url", sa.String(length=255), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("house_id", sa.Integer(), nullable=True),
        sa.Column("party_id", sa.Integer(), nullable=True),
        sa.Column("province_id", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("pa_link", sa.String(length=255), nullable=True),
        sa.Column(
            "current", sa.Boolean(), server_default=sa.text(u"true"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["house_id"], ["house.id"], name=op.f("fk_member_house_id_house")
        ),
        sa.ForeignKeyConstraint(
            ["party_id"], ["party.id"], name=op.f("fk_member_party_id_party")
        ),
        sa.ForeignKeyConstraint(
            ["province_id"],
            ["province.id"],
            name=op.f("fk_member_province_id_province"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_member")),
        sa.UniqueConstraint("name", name=op.f("member_name_key")),
        sa.UniqueConstraint("pa_link", name=op.f("member_pa_link_key")),
    )
    op.create_table(
        "house",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("name_short", sa.String(length=20), nullable=False),
        sa.Column("sphere", sa.String(length=20), nullable=False),
        sa.Column("contact_details", sa.Text(), nullable=True),
        sa.Column("speaker_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["speaker_id"], ["member.id"], name=op.f("fk_house_speaker_id_member")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_house")),
    )
    op.create_table(
        "bill",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("date_of_introduction", sa.Date(), nullable=True),
        sa.Column("date_of_assent", sa.Date(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("act_name", sa.String(length=250), nullable=True),
        sa.Column("introduced_by", sa.String(length=250), nullable=True),
        sa.Column("status_id", sa.Integer(), nullable=True),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("place_of_introduction_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["place_of_introduction_id"],
            ["house.id"],
            name=op.f("fk_bill_place_of_introduction_id_house"),
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["bill_status.id"],
            name=op.f("fk_bill_status_id_bill_status"),
        ),
        sa.ForeignKeyConstraint(
            ["type_id"], ["bill_type.id"], name=op.f("fk_bill_type_id_bill_type")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bill")),
        sa.UniqueConstraint(
            "number", "year", "type_id", name="bill_number_year_type_id_key"
        ),
    )
    op.create_index(op.f("ix_bill_created_at"), "bill", ["created_at"], unique=False)
    op.create_index(op.f("ix_bill_updated_at"), "bill", ["updated_at"], unique=False)
    op.create_table(
        "bill_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("bill_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=True),
        sa.Column(
            "enacted", sa.Boolean(), server_default=sa.text(u"false"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bill.id"],
            name=op.f("fk_bill_versions_bill_id_bill"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
            name=op.f("fk_bill_versions_file_id_file"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bill_versions")),
    )
    op.create_index(
        op.f("ix_member_created_at"), "member", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_member_current"), "member", ["current"], unique=False)
    op.create_index(
        op.f("ix_member_updated_at"), "member", ["updated_at"], unique=False
    )
    op.create_table(
        "membership_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membership_type")),
    )
    op.create_table(
        "minister",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_minister")),
    )
    op.create_index(
        op.f("ix_minister_created_at"), "minister", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_minister_updated_at"), "minister", ["updated_at"], unique=False
    )
    op.create_table(
        "organisation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("domain", sa.String(length=100), nullable=False),
        sa.Column("paid_subscriber", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expiry", sa.Date(), nullable=True),
        sa.Column("contact", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organisation")),
    )
    op.create_table(
        "organisation_committee",
        sa.Column("organisation_id", sa.Integer(), nullable=True),
        sa.Column("committee_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["committee_id"],
            ["committee.id"],
            name=op.f("fk_organisation_committee_committee_id_committee"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisation.id"],
            name=op.f("fk_organisation_committee_organisation_id_organisation"),
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "page",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "date",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=True,
        ),
        sa.Column(
            "show_files", sa.Boolean(), server_default=sa.text(u"true"), nullable=False
        ),
        sa.Column(
            "featured", sa.Boolean(), server_default=sa.text(u"false"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_page")),
    )
    op.create_index(op.f("ix_page_created_at"), "page", ["created_at"], unique=False)
    op.create_index(op.f("ix_page_date"), "page", ["date"], unique=False)
    op.create_index(op.f("ix_page_featured"), "page", ["featured"], unique=False)
    op.create_index(op.f("ix_page_slug"), "page", ["slug"], unique=True)
    op.create_table(
        "page_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
            name=op.f("fk_page_files_file_id_file"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["page.id"],
            name=op.f("fk_page_files_page_id_page"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_page_files")),
    )
    op.create_index(
        op.f("ix_page_files_file_id"), "page_files", ["file_id"], unique=False
    )
    op.create_index(
        op.f("ix_page_files_page_id"), "page_files", ["page_id"], unique=False
    )
    op.create_table(
        "party",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_party")),
    )
    op.create_table(
        "policy_document",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("nid", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_document")),
    )
    op.create_index(
        op.f("ix_policy_document_created_at"),
        "policy_document",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_document_updated_at"),
        "policy_document",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "policy_document_file_join",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("policy_document_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
            name=op.f("fk_policy_document_file_join_file_id_file"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["policy_document_id"],
            ["policy_document.id"],
            name=op.f(
                "fk_policy_document_file_join_policy_document_id_policy_document"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_document_file_join")),
    )
    op.create_index(
        op.f("ix_policy_document_file_join_file_id"),
        "policy_document_file_join",
        ["file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_policy_document_file_join_policy_document_id"),
        "policy_document_file_join",
        ["policy_document_id"],
        unique=False,
    )
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column(
            "featured", sa.Boolean(), server_default=sa.text(u"false"), nullable=False
        ),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "date",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_post")),
    )
    op.create_index(op.f("ix_post_created_at"), "post", ["created_at"], unique=False)
    op.create_index(op.f("ix_post_date"), "post", ["date"], unique=False)
    op.create_index(op.f("ix_post_featured"), "post", ["featured"], unique=False)
    op.create_index(op.f("ix_post_slug"), "post", ["slug"], unique=True)
    op.create_table(
        "post_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
            name=op.f("fk_post_files_file_id_file"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
            name=op.f("fk_post_files_post_id_post"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_post_files")),
    )
    op.create_index(
        op.f("ix_post_files_file_id"), "post_files", ["file_id"], unique=False
    )
    op.create_index(
        op.f("ix_post_files_post_id"), "post_files", ["post_id"], unique=False
    )
    op.create_table(
        "province",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_province")),
    )
    op.create_table(
        "question_reply",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("minister_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("question_number", sa.String(length=255), nullable=True),
        sa.Column("nid", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["minister_id"],
            ["minister.id"],
            name=op.f("fk_question_reply_minister_id_minister"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_reply")),
    )
    op.create_index(
        op.f("ix_question_reply_created_at"),
        "question_reply",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_reply_updated_at"),
        "question_reply",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "question_reply_file_join",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_reply_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
            name=op.f("fk_question_reply_file_join_file_id_file"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_reply_id"],
            ["question_reply.id"],
            name=op.f("fk_question_reply_file_join_question_reply_id_question_reply"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_reply_file_join")),
    )
    op.create_index(
        op.f("ix_question_reply_file_join_file_id"),
        "question_reply_file_join",
        ["file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_reply_file_join_question_reply_id"),
        "question_reply_file_join",
        ["question_reply_id"],
        unique=False,
    )
    op.create_table(
        "redirect",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nid", sa.Integer(), nullable=True),
        sa.Column("old_url", sa.String(length=250), nullable=False),
        sa.Column("new_url", sa.String(length=250), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_redirect")),
    )
    op.create_index(op.f("ix_redirect_old_url"), "redirect", ["old_url"], unique=True)
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
        sa.UniqueConstraint("name", name=op.f("role_name_key")),
    )
    op.create_table(
        "roles_users",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"], ["role.id"], name=op.f("fk_roles_users_role_id_role")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_roles_users_user_id_user")
        ),
    )
    op.create_table(
        "saved_search",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("search", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=True),
        sa.Column("committee_id", sa.Integer(), nullable=True),
        sa.Column(
            "last_alerted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["committee_id"],
            ["committee.id"],
            name=op.f("fk_saved_search_committee_id_committee"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_saved_search_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_search")),
    )
    op.create_index(
        op.f("ix_saved_search_created_at"), "saved_search", ["created_at"], unique=False
    )
    op.create_table(
        "soundcloud_track",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("uri", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"], ["file.id"], name=op.f("fk_soundcloud_track_file_id_file")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_soundcloud_track")),
        sa.UniqueConstraint("file_id", name=op.f("soundcloud_track_file_id_key")),
    )
    op.create_table(
        "soundcloud_track_retry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("soundcloud_track_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["soundcloud_track_id"],
            ["soundcloud_track.id"],
            name=op.f("fk_soundcloud_track_retry_soundcloud_track_id_soundcloud_track"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_soundcloud_track_retry")),
    )
    op.create_table(
        "tabled_committee_report",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("nid", sa.Integer(), nullable=True),
        sa.Column("committee_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["committee_id"],
            ["committee.id"],
            name=op.f("fk_tabled_committee_report_committee_id_committee"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tabled_committee_report")),
    )
    op.create_index(
        op.f("ix_tabled_committee_report_committee_id"),
        "tabled_committee_report",
        ["committee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tabled_committee_report_created_at"),
        "tabled_committee_report",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tabled_committee_report_updated_at"),
        "tabled_committee_report",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "tabled_committee_report_file_join",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tabled_committee_report_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
            name=op.f("fk_tabled_committee_report_file_join_file_id_file"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tabled_committee_report_id"],
            ["tabled_committee_report.id"],
            name=op.f(
                "fk_tabled_committee_report_file_join_tabled_committee_report_id_tabled_committee_report"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_tabled_committee_report_file_join")
        ),
    )
    op.create_index(
        op.f("ix_tabled_committee_report_file_join_file_id"),
        "tabled_committee_report_file_join",
        ["file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tabled_committee_report_file_join_tabled_committee_report_id"),
        "tabled_committee_report_file_join",
        ["tabled_committee_report_id"],
        unique=False,
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("password", sa.String(length=255), server_default="", nullable=False),
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text(u"true"), nullable=True
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_ip", sa.String(length=100), nullable=True),
        sa.Column("current_login_ip", sa.String(length=100), nullable=True),
        sa.Column("login_count", sa.Integer(), nullable=True),
        sa.Column("subscribe_daily_schedule", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.Column("expiry", sa.Date(), nullable=True),
        sa.Column("organisation_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisation.id"],
            name=op.f("fk_user_organisation_id_organisation"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_index(op.f("ix_user_created_at"), "user", ["created_at"], unique=False)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_updated_at"), "user", ["updated_at"], unique=False)
    op.create_table(
        "user_committee",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("committee_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["committee_id"],
            ["committee.id"],
            name=op.f("fk_user_committee_committee_id_committee"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_user_committee_user_id_user"),
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "user_committee_alerts",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("committee_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["committee_id"],
            ["committee.id"],
            name=op.f("fk_user_committee_alerts_committee_id_committee"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_user_committee_alerts_user_id_user"),
            ondelete="CASCADE",
        ),
    )
    op.create_table(
        "user_following",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("committee_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(u"now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["committee_id"],
            ["committee.id"],
            name=op.f("fk_user_following_committee_id_committee"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_user_following_user_id_user"),
            ondelete="CASCADE",
        ),
    )
    op.create_index(
        op.f("ix_user_following_created_at"),
        "user_following",
        ["created_at"],
        unique=False,
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_following_created_at"), table_name="user_following")
    op.drop_table("user_following")
    op.drop_table("user_committee_alerts")
    op.drop_table("user_committee")
    op.drop_index(op.f("ix_user_updated_at"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index(op.f("ix_user_created_at"), table_name="user")
    op.drop_table("user")
    op.drop_index(
        op.f("ix_tabled_committee_report_file_join_tabled_committee_report_id"),
        table_name="tabled_committee_report_file_join",
    )
    op.drop_index(
        op.f("ix_tabled_committee_report_file_join_file_id"),
        table_name="tabled_committee_report_file_join",
    )
    op.drop_table("tabled_committee_report_file_join")
    op.drop_index(
        op.f("ix_tabled_committee_report_updated_at"),
        table_name="tabled_committee_report",
    )
    op.drop_index(
        op.f("ix_tabled_committee_report_created_at"),
        table_name="tabled_committee_report",
    )
    op.drop_index(
        op.f("ix_tabled_committee_report_committee_id"),
        table_name="tabled_committee_report",
    )
    op.drop_table("tabled_committee_report")
    op.drop_table("soundcloud_track_retry")
    op.drop_table("soundcloud_track")
    op.drop_index(op.f("ix_saved_search_created_at"), table_name="saved_search")
    op.drop_table("saved_search")
    op.drop_table("roles_users")
    op.drop_table("role")
    op.drop_index(op.f("ix_redirect_old_url"), table_name="redirect")
    op.drop_table("redirect")
    op.drop_index(
        op.f("ix_question_reply_file_join_question_reply_id"),
        table_name="question_reply_file_join",
    )
    op.drop_index(
        op.f("ix_question_reply_file_join_file_id"),
        table_name="question_reply_file_join",
    )
    op.drop_table("question_reply_file_join")
    op.drop_index(op.f("ix_question_reply_updated_at"), table_name="question_reply")
    op.drop_index(op.f("ix_question_reply_created_at"), table_name="question_reply")
    op.drop_table("question_reply")
    op.drop_table("province")
    op.drop_index(op.f("ix_post_files_post_id"), table_name="post_files")
    op.drop_index(op.f("ix_post_files_file_id"), table_name="post_files")
    op.drop_table("post_files")
    op.drop_index(op.f("ix_post_slug"), table_name="post")
    op.drop_index(op.f("ix_post_featured"), table_name="post")
    op.drop_index(op.f("ix_post_date"), table_name="post")
    op.drop_index(op.f("ix_post_created_at"), table_name="post")
    op.drop_table("post")
    op.drop_index(
        op.f("ix_policy_document_file_join_policy_document_id"),
        table_name="policy_document_file_join",
    )
    op.drop_index(
        op.f("ix_policy_document_file_join_file_id"),
        table_name="policy_document_file_join",
    )
    op.drop_table("policy_document_file_join")
    op.drop_index(op.f("ix_policy_document_updated_at"), table_name="policy_document")
    op.drop_index(op.f("ix_policy_document_created_at"), table_name="policy_document")
    op.drop_table("policy_document")
    op.drop_table("party")
    op.drop_index(op.f("ix_page_files_page_id"), table_name="page_files")
    op.drop_index(op.f("ix_page_files_file_id"), table_name="page_files")
    op.drop_table("page_files")
    op.drop_index(op.f("ix_page_slug"), table_name="page")
    op.drop_index(op.f("ix_page_featured"), table_name="page")
    op.drop_index(op.f("ix_page_date"), table_name="page")
    op.drop_index(op.f("ix_page_created_at"), table_name="page")
    op.drop_table("page")
    op.drop_table("organisation_committee")
    op.drop_table("organisation")
    op.drop_index(op.f("ix_minister_updated_at"), table_name="minister")
    op.drop_index(op.f("ix_minister_created_at"), table_name="minister")
    op.drop_table("minister")
    op.drop_table("membership_type")
    op.drop_index(op.f("ix_member_updated_at"), table_name="member")
    op.drop_index(op.f("ix_member_current"), table_name="member")
    op.drop_index(op.f("ix_member_created_at"), table_name="member")
    op.drop_table("member")
    op.drop_table("house")
    op.drop_index(
        op.f("ix_gazette_file_join_gazette_id"), table_name="gazette_file_join"
    )
    op.drop_index(op.f("ix_gazette_file_join_file_id"), table_name="gazette_file_join")
    op.drop_table("gazette_file_join")
    op.drop_index(op.f("ix_gazette_updated_at"), table_name="gazette")
    op.drop_index(op.f("ix_gazette_created_at"), table_name="gazette")
    op.drop_table("gazette")
    op.drop_table("file")
    op.drop_table("featured")
    op.drop_index(op.f("ix_event_files_id"), table_name="event_files")
    op.drop_index(op.f("ix_event_files_file_id"), table_name="event_files")
    op.drop_index(op.f("ix_event_files_event_id"), table_name="event_files")
    op.drop_table("event_files")
    op.drop_table("event_bills")
    op.drop_index(op.f("ix_event_updated_at"), table_name="event")
    op.drop_index(op.f("ix_event_type"), table_name="event")
    op.drop_index(op.f("ix_event_member_id"), table_name="event")
    op.drop_index(op.f("ix_event_id"), table_name="event")
    op.drop_index(op.f("ix_event_house_id"), table_name="event")
    op.drop_index(op.f("ix_event_featured"), table_name="event")
    op.drop_index(op.f("ix_event_created_at"), table_name="event")
    op.drop_index(op.f("ix_event_committee_id"), table_name="event")
    op.drop_table("event")
    op.drop_index(op.f("ix_email_template_created_at"), table_name="email_template")
    op.drop_table("email_template")
    op.drop_index(
        op.f("ix_daily_schedule_file_join_file_id"),
        table_name="daily_schedule_file_join",
    )
    op.drop_index(
        op.f("ix_daily_schedule_file_join_daily_schedule_id"),
        table_name="daily_schedule_file_join",
    )
    op.drop_table("daily_schedule_file_join")
    op.drop_index(op.f("ix_daily_schedule_updated_at"), table_name="daily_schedule")
    op.drop_index(op.f("ix_daily_schedule_house_id"), table_name="daily_schedule")
    op.drop_index(op.f("ix_daily_schedule_created_at"), table_name="daily_schedule")
    op.drop_table("daily_schedule")
    op.drop_index(
        op.f("ix_committee_question_file_join_file_id"),
        table_name="committee_question_file_join",
    )
    op.drop_index(
        op.f("ix_committee_question_file_join_committee_question_id"),
        table_name="committee_question_file_join",
    )
    op.drop_table("committee_question_file_join")
    op.drop_index(op.f("ix_committee_question_year"), table_name="committee_question")
    op.drop_index(
        op.f("ix_committee_question_written_number"), table_name="committee_question"
    )
    op.drop_index(
        op.f("ix_committee_question_updated_at"), table_name="committee_question"
    )
    op.drop_index(
        op.f("ix_committee_question_source_file_id"), table_name="committee_question"
    )
    op.drop_index(
        op.f("ix_committee_question_question_number"), table_name="committee_question"
    )
    op.drop_index(
        op.f("ix_committee_question_president_number"), table_name="committee_question"
    )
    op.drop_index(
        op.f("ix_committee_question_oral_number"), table_name="committee_question"
    )
    op.drop_index(
        op.f("ix_committee_question_deputy_president_number"),
        table_name="committee_question",
    )
    op.drop_index(
        op.f("ix_committee_question_created_at"), table_name="committee_question"
    )
    op.drop_index(op.f("ix_committee_question_code"), table_name="committee_question")
    op.drop_table("committee_question")
    op.drop_table("committee_members")
    op.drop_index("meeting_member_ix", table_name="committee_meeting_attendance")
    op.drop_index(
        op.f("ix_committee_meeting_attendance_updated_at"),
        table_name="committee_meeting_attendance",
    )
    op.drop_index(
        op.f("ix_committee_meeting_attendance_created_at"),
        table_name="committee_meeting_attendance",
    )
    op.drop_table("committee_meeting_attendance")
    op.drop_index(op.f("ix_committee_updated_at"), table_name="committee")
    op.drop_index(op.f("ix_committee_created_at"), table_name="committee")
    op.drop_table("committee")
    op.drop_index(op.f("ix_call_for_comment_updated_at"), table_name="call_for_comment")
    op.drop_index(op.f("ix_call_for_comment_created_at"), table_name="call_for_comment")
    op.drop_table("call_for_comment")
    op.drop_table("bill_versions")
    op.drop_table("bill_type")
    op.drop_table("bill_status")
    op.drop_index(op.f("ix_bill_updated_at"), table_name="bill")
    op.drop_index(op.f("ix_bill_created_at"), table_name="bill")
    op.drop_table("bill")
    ### end Alembic commands ###
