"""add sphere to house

Revision ID: 376804c871b4
Revises: 3a36d926aaf2
Create Date: 2018-01-09 16:00:43.753251

"""

# revision identifiers, used by Alembic.
revision = '376804c871b4'
down_revision = '3a36d926aaf2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house', sa.Column('sphere', sa.String(length=20), nullable=False, server_default='national'))
    op.alter_column('house', 'sphere', server_default=None)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('house', 'sphere')
    ### end Alembic commands ###
