"""simplify_featured_content

Revision ID: 3969d67f5cb6
Revises: 5067bfd9852c
Create Date: 2015-02-24 11:25:14.818633

"""

# revision identifiers, used by Alembic.
revision = '3969d67f5cb6'
down_revision = '5067bfd9852c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'featured_tabled_committee_report_join')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'featured_tabled_committee_report_join',
    sa.Column(u'featured_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'tabled_committee_report_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint([u'featured_id'], [u'featured.id'], name=u'featured_tabled_committee_report_join_featured_id_fkey'),
    sa.ForeignKeyConstraint([u'tabled_committee_report_id'], [u'tabled_committee_report.id'], name=u'featured_tabled_committee_repor_tabled_committee_report_id_fkey')
    )
    ### end Alembic commands ###
