"""remove cte from questions

Revision ID: 3a36d926aaf2
Revises: 191f4dbb7278
Create Date: 2017-08-25 15:54:23.864810

"""

# revision identifiers, used by Alembic.
revision = '3a36d926aaf2'
down_revision = '191f4dbb7278'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'committee_question_committee_id_fkey', 'committee_question', type_='foreignkey')
    op.drop_column('committee_question', 'committee_id')
    op.drop_constraint(u'question_reply_committee_id_fkey', 'question_reply', type_='foreignkey')
    op.drop_column('question_reply', 'committee_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_reply', sa.Column('committee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'question_reply_committee_id_fkey', 'question_reply', 'committee', ['committee_id'], ['id'], ondelete=u'SET NULL')
    op.add_column('committee_question', sa.Column('committee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'committee_question_committee_id_fkey', 'committee_question', 'committee', ['committee_id'], ['id'], ondelete=u'SET NULL')
    ### end Alembic commands ###
