"""bill year is required

Revision ID: 3b3a939bf12c
Revises: 2ff6718f2a66
Create Date: 2015-02-11 14:47:11.032734

"""

# revision identifiers, used by Alembic.
revision = '3b3a939bf12c'
down_revision = '2ff6718f2a66'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bill', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bill', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
