"""remove_api_key

Revision ID: 3bf259540e8b
Revises: 12ce767acbcf
Create Date: 2015-10-08 08:21:19.735453

"""

# revision identifiers, used by Alembic.
revision = '3bf259540e8b'
down_revision = '12ce767acbcf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_key')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'api_key_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'api_key_pkey'),
    sa.UniqueConstraint('key', name=u'api_key_key_key'),
    sa.UniqueConstraint('user_id', name=u'api_key_user_id_key')
    )
    ### end Alembic commands ###
