"""Add featured column to petition_files table

Revision ID: 3ec66b8763d
Revises: 163aa83c330
Create Date: 2025-09-11 07:13:19.510538

"""

# revision identifiers, used by Alembic.
revision = '3ec66b8763d'
down_revision = '163aa83c330'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # Add the featured column as nullable first
    op.add_column('petition_files', sa.Column('featured', sa.Boolean(), nullable=True))
    
    # Update all existing records to have featured=False
    op.execute("UPDATE petition_files SET featured = FALSE WHERE featured IS NULL")
    
    # Now make the column non-nullable
    op.alter_column('petition_files', 'featured', nullable=False)
    
    op.alter_column('petition_status', 'step',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('petition_status', 'step',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('petition_files', 'featured')
    ### end Alembic commands ###
