"""no_hitlog

Revision ID: 4037703104ea
Revises: 4c7e8d899149
Create Date: 2015-03-17 09:58:38.345303

"""

# revision identifiers, used by Alembic.
revision = '4037703104ea'
down_revision = '4c7e8d899149'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'hit_log')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'hit_log',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column(u'ip_addr', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column(u'user_agent', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column(u'url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id', name=u'hit_log_pkey')
    )
    ### end Alembic commands ###
