"""attendance tweaks

Revision ID: 44d9d3bf2abb
Revises: 3559c36f279d
Create Date: 2015-07-21 17:28:29.177619

"""

# revision identifiers, used by Alembic.
revision = '44d9d3bf2abb'
down_revision = '3559c36f279d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE committee_meeting_attendance")
    op.drop_column('committee_meeting_attendance', 'alternate_member')
    op.execute("CREATE TYPE meeting_attendance_enum AS ENUM ('A', 'AP', 'DE', 'L', 'LDE', 'P', 'Y')")
    op.add_column('committee_meeting_attendance', sa.Column('alternate_member', sa.Boolean(), server_default=sa.text(u'false'), nullable=False))
    op.add_column('committee_meeting_attendance', sa.Column('attendance', sa.Enum('A', 'AP', 'DE', 'L', 'LDE', 'P', 'Y', name='meeting_attendance_enum'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('committee_meeting_attendance', 'attendance')
    op.execute("DROP TYPE meeting_attendance_enum")
    op.drop_column('committee_meeting_attendance', 'alternate_member')
    op.add_column('committee_meeting_attendance', sa.Column('alternate_member', sa.Boolean(), nullable=True))
    ### end Alembic commands ###
