"""test

Revision ID: 485814144844
Revises: 
Create Date: 2015-01-14 11:42:07.270925

"""

# revision identifiers, used by Alembic.
revision = '485814144844'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('committee', sa.Column('ad_hoc', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('committee', 'ad_hoc')
    ### end Alembic commands ###
