"""Add user name column.

Revision ID: 4b73b02d9536
Revises: 2c95cab0a8d8
Create Date: 2015-01-16 11:06:33.131906

"""

# revision identifiers, used by Alembic.
revision = '4b73b02d9536'
down_revision = '2c95cab0a8d8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    ### end Alembic commands ###
