"""Allow for null-valued urls in redirect table.

Revision ID: 4c3554286996
Revises: 516aebc76ca8
Create Date: 2015-01-30 10:34:02.938038

"""

# revision identifiers, used by Alembic.
revision = '4c3554286996'
down_revision = '516aebc76ca8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('redirect', 'new_url',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('redirect', 'new_url',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    ### end Alembic commands ###
