"""daily_schedule_files

Revision ID: 4c8a62ba844a
Revises: 4a70c03d91b6
Create Date: 2015-03-18 08:56:22.434817

"""

# revision identifiers, used by Alembic.
revision = '4c8a62ba844a'
down_revision = '4a70c03d91b6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE daily_schedule_file_join ADD COLUMN id SERIAL')
    op.alter_column('daily_schedule_file_join', 'daily_schedule_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_schedule_file_join', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(u'ix_daily_schedule_file_join_daily_schedule_id', 'daily_schedule_file_join', ['daily_schedule_id'], unique=False)
    op.create_index(u'ix_daily_schedule_file_join_file_id', 'daily_schedule_file_join', ['file_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_daily_schedule_file_join_file_id', table_name='daily_schedule_file_join')
    op.drop_index(u'ix_daily_schedule_file_join_daily_schedule_id', table_name='daily_schedule_file_join')
    op.alter_column('daily_schedule_file_join', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_schedule_file_join', 'daily_schedule_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('daily_schedule_file_join', 'id')
    ### end Alembic commands ###
