"""event_files

Revision ID: 4d3c2b4ceacb
Revises: 304c3434c2f9
Create Date: 2015-03-17 11:51:44.861586

"""

# revision identifiers, used by Alembic.
revision = '4d3c2b4ceacb'
down_revision = '304c3434c2f9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('related', name='event_file_type_enum'), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_event_files_event_id', 'event_files', ['event_id'], unique=False)
    op.create_index(u'ix_event_files_file_id', 'event_files', ['file_id'], unique=False)
    op.create_index(u'ix_event_files_id', 'event_files', ['id'], unique=False)

    op.execute("""
        insert into event_files (event_id, file_id, type)
        select c.event_id, c.file_id, 'related'
        from content c
        where c.file_id is not null
        """)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_event_files_id', table_name='event_files')
    op.drop_index(u'ix_event_files_file_id', table_name='event_files')
    op.drop_index(u'ix_event_files_event_id', table_name='event_files')
    op.drop_table('event_files')
    op.drop_table('event_files')
    op.execute('drop type event_file_type_enum')
    ### end Alembic commands ###
