"""policy_document_files

Revision ID: 4d5eb029f9cc
Revises: 1986f3e16316
Create Date: 2015-03-18 09:14:29.169460

"""

# revision identifiers, used by Alembic.
revision = '4d5eb029f9cc'
down_revision = '1986f3e16316'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE policy_document_file_join ADD COLUMN id SERIAL')
    op.alter_column('policy_document_file_join', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('policy_document_file_join', 'policy_document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(u'ix_policy_document_file_join_file_id', 'policy_document_file_join', ['file_id'], unique=False)
    op.create_index(u'ix_policy_document_file_join_policy_document_id', 'policy_document_file_join', ['policy_document_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_policy_document_file_join_policy_document_id', table_name='policy_document_file_join')
    op.drop_index(u'ix_policy_document_file_join_file_id', table_name='policy_document_file_join')
    op.alter_column('policy_document_file_join', 'policy_document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('policy_document_file_join', 'file_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('policy_document_file_join', 'id')
    ### end Alembic commands ###
