"""pages

Revision ID: 5067bfd9852c
Revises: 349371b86798
Create Date: 2015-02-24 08:47:03.119619

"""

# revision identifiers, used by Alembic.
revision = '5067bfd9852c'
down_revision = '349371b86798'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_page_created_at', 'page', ['created_at'], unique=False)
    op.create_index(u'ix_page_slug', 'page', ['slug'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_page_slug', table_name='page')
    op.drop_index(u'ix_page_created_at', table_name='page')
    op.drop_table('page')
    ### end Alembic commands ###
