"""member names unique

Revision ID: 51dd553fdf8b
Revises: 558448506c78
Create Date: 2015-11-11 08:12:44.586447

"""

# revision identifiers, used by Alembic.
revision = '51dd553fdf8b'
down_revision = '558448506c78'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('member_name_key'), 'member', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('member_name_key'), 'member', type_='unique')
    ### end Alembic commands ###
