"""pages_show_files

Revision ID: 51e2dcf51b13
Revises: 2c5f5b0bbd94
Create Date: 2015-04-10 09:33:57.025023

"""

# revision identifiers, used by Alembic.
revision = '51e2dcf51b13'
down_revision = '2c5f5b0bbd94'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('show_files', sa.Boolean(), server_default=sa.text(u'true'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'show_files')
    ### end Alembic commands ###
