"""petition fixes

Revision ID: 52758903e30
Revises: 3ec66b8763d
Create Date: 2025-09-30 14:06:52.019069

"""

# revision identifiers, used by Alembic.
revision = '52758903e30'
down_revision = '3ec66b8763d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('petition_status', 'step',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('petition_status', 'step',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
