"""User notification subscriptions.

Revision ID: 544fa615efc3
Revises: 1db076d08d78
Create Date: 2015-01-21 15:43:52.736862

"""

# revision identifiers, used by Alembic.
revision = '544fa615efc3'
down_revision = '1db076d08d78'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscribe_bill', sa.Boolean()))
    op.add_column('user', sa.Column('subscribe_call_for_comment', sa.Boolean()))
    op.add_column('user', sa.Column('subscribe_daily_schedule', sa.Boolean()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscribe_daily_schedule')
    op.drop_column('user', 'subscribe_call_for_comment')
    op.drop_column('user', 'subscribe_bill')
    ### end Alembic commands ###
