"""committee question indexes

Revision ID: 5647a4255cdc
Revises: 89b5386b363
Create Date: 2015-07-17 08:30:20.548949

"""

# revision identifiers, used by Alembic.
revision = '5647a4255cdc'
down_revision = '89b5386b363'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_committee_question_code', table_name=u'committee_question')
    op.create_index(u'ix_committee_question_code', 'committee_question', ['code'], unique=False)

    op.create_index(u'date_code_ix', 'committee_question', ['date', 'code'], unique=True)
    op.create_index(u'date_oral_number_ix', 'committee_question', ['date', 'house_id', 'oral_number'], unique=True)
    op.create_index(u'date_written_number_ix', 'committee_question', ['date', 'house_id', 'written_number'], unique=True)
    op.create_index(u'date_president_number_ix', 'committee_question', ['date', 'house_id', 'president_number'], unique=True)
    op.create_index(u'date_deputy_president_number_ix', 'committee_question', ['date', 'house_id', 'deputy_president_number'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'date_code_ix', table_name='committee_question')
    op.drop_index(u'date_oral_number_ix', table_name='committee_question')
    op.drop_index(u'date_written_number_ix', table_name='committee_question')
    op.drop_index(u'date_president_number_ix', table_name='committee_question')
    op.drop_index(u'date_deputy_president_number_ix', table_name='committee_question')

    op.drop_index(u'ix_committee_question_code', table_name='committee_question')
    op.create_index(u'ix_committee_question_code', u'committee_question', [u'code'], unique=True)
    ### end Alembic commands ###
