"""Committee monitored field

Revision ID: 5e88e38a231
Revises: 299e1d15a55f
Create Date: 2018-09-03 09:24:52.787827

"""

# revision identifiers, used by Alembic.
revision = '5e88e38a231'
down_revision = '299e1d15a55f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('committee', sa.Column('monitored', sa.Boolean(), server_default=sa.text(u'true'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('committee', 'monitored')
    ### end Alembic commands ###
