"""bill-versions-enacted

Revision ID: 825d555af49
Revises: 3101ec185bdf
Create Date: 2015-12-08 08:35:52.703472

"""

# revision identifiers, used by Alembic.
revision = '825d555af49'
down_revision = '3101ec185bdf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_versions', sa.Column('enacted', sa.Boolean(), server_default=sa.text(u'false'), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill_versions', 'enacted')
    ### end Alembic commands ###
