"""change answered_on to date

Revision ID: 89b5386b363
Revises: 2c6a08d9cdef
Create Date: 2015-07-17 08:16:16.487287

"""

# revision identifiers, used by Alembic.
revision = '89b5386b363'
down_revision = '2c6a08d9cdef'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('alter table committee_question rename column answered_on to date');
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('alter table committee_question rename column date to answered_on');
    ### end Alembic commands ###
