"""Add tabled_committee_report constraint

Revision ID: 8cbc3d8dd55
Revises: 17570e7e200b
Create Date: 2016-08-31 10:19:49.128041

"""

# revision identifiers, used by Alembic.
revision = '8cbc3d8dd55'
down_revision = '17570e7e200b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tabled_committee_report', 'committee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_tabled_committee_report_committee_id'), 'tabled_committee_report', ['committee_id'], unique=False)
    op.drop_constraint(u'tabled_committee_report_committee_id_fkey', 'tabled_committee_report', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tabled_committee_report_committee_id_committee'), 'tabled_committee_report', 'committee', ['committee_id'], ['id'])
    op.drop_column('tabled_committee_report', 'summary')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabled_committee_report', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_tabled_committee_report_committee_id_committee'), 'tabled_committee_report', type_='foreignkey')
    op.create_foreign_key(u'tabled_committee_report_committee_id_fkey', 'tabled_committee_report', 'committee', ['committee_id'], ['id'], ondelete=u'SET NULL')
    op.drop_index(op.f('ix_tabled_committee_report_committee_id'), table_name='tabled_committee_report')
    op.alter_column('tabled_committee_report', 'committee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
