"""question_to nullable

Revision ID: 985ba1ea25b
Revises: 269d21941a3a
Create Date: 2015-07-27 20:59:50.500287

"""

# revision identifiers, used by Alembic.
revision = '985ba1ea25b'
down_revision = '269d21941a3a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('committee_question', 'asked_by_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('committee_question', 'question_to_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('committee_question', 'question_to_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('committee_question', 'asked_by_name',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    ### end Alembic commands ###
