"""Make petition event title nullable

Revision ID: a1b2c3d4e5f6
Revises: 52758903e30
Create Date: 2025-11-06 00:00:00.000000

"""

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '52758903e30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('petition_event', 'title',
                    existing_type=sa.VARCHAR(length=1024),
                    nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('petition_event', 'title',
                    existing_type=sa.VARCHAR(length=1024),
                    nullable=False)
    ### end Alembic commands ###