"""file info

Revision ID: b432bbc7598
Revises: 3d9034ad2d7d
Create Date: 2015-03-29 12:03:23.449687

"""

# revision identifiers, used by Alembic.
revision = 'b432bbc7598'
down_revision = '3d9034ad2d7d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('file_bytes', sa.BigInteger(), nullable=True))
    op.drop_column('file', u'duration')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column(u'duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('file', 'file_bytes')
    ### end Alembic commands ###
