"""Add uniquifier column

Revision ID: e02ab1542a
Revises: a8ee5b414e
Create Date: 2023-07-18 10:54:26.257951

"""

# revision identifiers, used by Alembic.
revision = 'e02ab1542a'
down_revision = 'a8ee5b414e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fs_uniquifier', sa.String(length=64), server_default='', nullable=True))
    ### end Alembic commands ###

    # update existing rows with unique fs_uniquifier
    import uuid
    user_table = sa.Table('user', sa.MetaData(), sa.Column('id', sa.Integer, primary_key=True),
                        sa.Column('fs_uniquifier', sa.String))
    conn = op.get_bind()
    for row in conn.execute(sa.select([user_table.c.id])):
        conn.execute(user_table.update().values(fs_uniquifier=uuid.uuid4().hex).where(user_table.c.id == row['id']))

    # finally - set nullable to false
    op.alter_column('user', 'fs_uniquifier', nullable=False)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fs_uniquifier')
    ### end Alembic commands ###
