"""Add Petitions to Meetings

Revision ID: fba65ba89b
Revises: 110910bedd
Create Date: 2025-06-26 10:12:52.612623

"""

# revision identifiers, used by Alembic.
revision = 'fba65ba89b'
down_revision = '110910bedd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_petitions',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('petition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_event_petitions_event_id_event'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['petition_id'], ['petition.id'], name=op.f('fk_event_petitions_petition_id_petition'), ondelete='CASCADE')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_petitions')
    ### end Alembic commands ###
